{% set name = "flask_request_id" %}
{% set version = "0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flask-request-id-{{ version }}.tar.gz
  sha256: f7595e059fd92869bbe7fcd288fb47d1a981e3f442ad75d59c79dde214682b4d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python {{ python_min }}
  run:
    - flask >=0.7
    - python >={{ python_min }}
    - wsgi-request-id >=0.2

test:
  imports:
    - flask_request_id
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/rhyselsmore/flask-request-id
  summary: Extract yourself some Request IDs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
